FROM python:3.10-slim

WORKDIR /opt/airflow

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    "strawberry-graphql[fastapi]" \
    pandas \
    s3fs \
    pyarrow

EXPOSE 8000

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]